// Code generated by go-swagger; DO NOT EDIT.

package hello_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewIDOfHelloEndpointParams creates a new IDOfHelloEndpointParams object
// with the default values initialized.
func NewIDOfHelloEndpointParams() *IDOfHelloEndpointParams {
	var ()
	return &IDOfHelloEndpointParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIDOfHelloEndpointParamsWithTimeout creates a new IDOfHelloEndpointParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIDOfHelloEndpointParamsWithTimeout(timeout time.Duration) *IDOfHelloEndpointParams {
	var ()
	return &IDOfHelloEndpointParams{

		timeout: timeout,
	}
}

// NewIDOfHelloEndpointParamsWithContext creates a new IDOfHelloEndpointParams object
// with the default values initialized, and the ability to set a context for a request
func NewIDOfHelloEndpointParamsWithContext(ctx context.Context) *IDOfHelloEndpointParams {
	var ()
	return &IDOfHelloEndpointParams{

		Context: ctx,
	}
}

// NewIDOfHelloEndpointParamsWithHTTPClient creates a new IDOfHelloEndpointParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIDOfHelloEndpointParamsWithHTTPClient(client *http.Client) *IDOfHelloEndpointParams {
	var ()
	return &IDOfHelloEndpointParams{
		HTTPClient: client,
	}
}

/*IDOfHelloEndpointParams contains all the parameters to send to the API endpoint
for the id of hello endpoint operation typically these are written to a http.Request
*/
type IDOfHelloEndpointParams struct {

	/*Name*/
	Name *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) WithTimeout(timeout time.Duration) *IDOfHelloEndpointParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) WithContext(ctx context.Context) *IDOfHelloEndpointParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) WithHTTPClient(client *http.Client) *IDOfHelloEndpointParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) WithName(name *string) *IDOfHelloEndpointParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the id of hello endpoint params
func (o *IDOfHelloEndpointParams) SetName(name *string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *IDOfHelloEndpointParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
